import { requestText, requestFields, type RequestData } from '../src/lib/rfq';
export const escapeHtml=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const shell=(title:string,body:string)=>'<!doctype html><html lang="en"><body style="margin:0;background:#f4f5f2;color:#171b1f;font:14px/1.6 Arial,sans-serif"><div style="max-width:760px;margin:auto;padding:32px"><div style="background:#0a0c0f;color:#d5f36b;padding:24px;font-size:28px">supploid.</div><div style="background:white;padding:28px"><h1 style="font-size:24px">'+escapeHtml(title)+'</h1>'+body+'</div><p>Supploid · <a href="mailto:info@supploid.com">info@supploid.com</a></p></div></body></html>';
function table(d:RequestData){return '<table style="border-collapse:collapse;width:100%;font-size:13px">'+requestFields(d).map(([label,value])=>'<tr><th scope="row" style="text-align:left;padding:10px 16px 10px 0;vertical-align:top;border-bottom:1px solid #ddd">'+escapeHtml(label)+'</th><td style="padding:10px 0;border-bottom:1px solid #ddd;white-space:pre-wrap;overflow-wrap:anywhere">'+escapeHtml(value)+'</td></tr>').join('')+'</table>';}
export function emails(d:RequestData,reference:string,notify:string){
 const aog=d.kind==='aog', company=d.kind==='quote'?(d.company||d.firstName+' '+d.lastName):'Premium support', details=requestText(d);
 const response=aog?'Your premium AOG request is with our team. This is a separate service available 24/7. Scope, commercial terms, and the next steps will be agreed directly.':'We received your inquiry. Fast quoting, documentation supplied. Availability, accompanying source documentation, and commercial terms will be confirmed in the offer.';
 const internal={from:'Supploid RFQ <rfq@supploid.com>',to:[notify],reply_to:d.email,subject:'['+(aog?'AOG':'RFQ')+'] '+reference+' — '+company,html:shell((aog?'Premium AOG':'Quote request')+' '+reference,table(d)),text:reference+'\n\n'+details};
 const customer={from:'Supploid <noreply@supploid.com>',to:[d.email],reply_to:aog?'aog@supploid.com':'info@supploid.com',subject:'We received your '+(aog?'premium AOG request':'inquiry')+' — '+reference,html:shell('Request received — '+reference,'<p>'+escapeHtml(response)+'</p>'+table(d)+'<p>For premium AOG escalation, email <a href="mailto:aog@supploid.com">aog@supploid.com</a> and include your reference.</p><p>No order has been placed by submitting this request.</p>'),text:'Request received — '+reference+'\n\n'+response+'\n\n'+details+'\n\nPremium AOG: aog@supploid.com. Include your reference.\nNo order has been placed by submitting this request.'};
 return {internal,customer};
}
