import { readFile,readdir,writeFile,mkdir } from 'node:fs/promises';
import path from 'node:path';
import { gzipSync } from 'node:zlib';
async function walk(dir){return (await Promise.all((await readdir(dir,{withFileTypes:true})).map(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]))).flat();}
const files=await walk('dist'), htmls=files.filter(f=>f.endsWith('.html'));const errors=[];const titles=new Set();
for(const file of htmls){const html=await readFile(file,'utf8');const title=html.match(/<title>(.*?)<\/title>/)?.[1];if(!title||titles.has(title))errors.push(`${file}: missing or duplicate title`);titles.add(title);if((html.match(/<h1(?:\s|>)/g)||[]).length!==1)errors.push(`${file}: h1 count`);for(const img of html.matchAll(/<img\b[^>]*>/g))if(!/width=/.test(img[0])||!/height=/.test(img[0]))errors.push(`${file}: image missing dimensions`);if(/\bPoland\b|\b(?:4|four)[ -]business[ -]hours?\b|\b(?:4|four)[ -]hour\b/i.test(html))errors.push(`${file}: obsolete country framing or quote turnaround wording`);if(/RESEND_API_KEY|TURNSTILE_SECRET_KEY|REFERENCE_SECRET/.test(html))errors.push(`${file}: server configuration leaked`);if(/AS9120|ASA-100|ISO 9001|AC 00-56|approved supplier/i.test(html))errors.push(`${file}: review prohibited claim`);for(const match of html.matchAll(/(?:href|src)="(\/[^"?#]*)(?:\?[^"#]*)?(?:#[^"]*)?"/g)){const target=match[1];if(target.startsWith('/api/'))continue;const local=path.join('dist',decodeURIComponent(target));if(!files.includes(local)&&!files.includes(path.join(local,'index.html')))errors.push(`${file}: missing local target ${target}`);}}
const inlineScripts=new Set();for(const file of htmls){const html=await readFile(file,'utf8');for(const m of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)){if(!m[1].includes('src=')&&!m[1].includes('application/ld+json')&&m[2].trim())inlineScripts.add(m[2]);}}
const scripts=files.filter(f=>f.endsWith('.js'));const jsBytes=(await Promise.all(scripts.map(async f=>{const source=await readFile(f);if(/RESEND_API_KEY|TURNSTILE_SECRET_KEY|REFERENCE_SECRET/.test(source.toString()))errors.push(`${f}: server configuration leaked`);return gzipSync(source).length;}))).reduce((a,b)=>a+b,0)+[...inlineScripts].reduce((sum,script)=>sum+gzipSync(script).length,0);
if(jsBytes>=120*1024)errors.push('First-party JS budget exceeded');const home=await readFile('dist/index.html','utf8');const assetUrls=[...new Set([...home.matchAll(/(?:src|href)="(\/[^"?#]+\.(?:css|js|woff2|webp))"/g)].map(m=>m[1]))];let homeBytes=Buffer.byteLength(home);for(const url of assetUrls)homeBytes+=(await readFile(path.join('dist',url))).byteLength;
const report={pages:htmls.length,firstPartyJavaScriptGzipBytes:jsBytes,homepageHtmlAndDirectAssetsBytes:homeBytes,errors,note:'Browser network measurement, third-party Turnstile overhead, Lighthouse, and field INP are separate checks.'};await mkdir('reports',{recursive:true});await writeFile('reports/build-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(errors.length)process.exitCode=1;
