import { readdir,readFile,writeFile,mkdir } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
const root=path.resolve('dist');
async function walk(dir){return (await Promise.all((await readdir(dir,{withFileTypes:true})).map(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]))).flat();}
const pages=(await walk(root)).filter(p=>p.endsWith('.html'));
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
await mkdir(path.join(root,'og'),{recursive:true});const routes=[];
for(const file of pages){const relative=path.relative(root,file);const route=relative==='index.html'?'/':relative==='404.html'?'/404/':'/'+relative.replace(/index\.html$/,'');const html=await readFile(file,'utf8');const title=(html.match(/<title>(.*?)<\/title>/)?.[1]||'Supploid').replace(/ \| Supploid$/,'').replaceAll('&amp;','&').replaceAll('&#39;',"'");const lines=[];let line='';for(const word of title.split(' ')){if((line+' '+word).length>31&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);const key=route.replace(/^\/+|\/+$/g,'').replaceAll('/','-')||'home';const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#0a0c0f"/><path d="M64 64H1136M64 548H1136" stroke="#333c43"/><text x="64" y="131" fill="#d5f36b" font-family="Arial,sans-serif" font-size="40">supploid.</text>${lines.slice(0,4).map((text,i)=>`<text x="64" y="${240+i*73}" fill="#f0f1ec" font-family="Arial,sans-serif" font-size="62" letter-spacing="-2">${escape(text)}</text>`).join('')}<text x="64" y="590" fill="#a6afb8" font-family="Arial,sans-serif" font-size="18" letter-spacing="3">AVIATION-LED. INDUSTRY-WIDE.</text><path d="M1080 563L1114 529M1080 529H1114V563" fill="none" stroke="#d5f36b" stroke-width="3"/></svg>`;await sharp(Buffer.from(svg)).png().toFile(path.join(root,'og',key+'.png'));if(!/404|privacy|terms/.test(route))routes.push(route);}
await writeFile(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.sort().map(route=>`<url><loc>https://supploid.com${route}</loc></url>`).join('')+'</urlset>\n');
const indexable=process.env.PUBLIC_INDEXABLE==='true';await writeFile(path.join(root,'robots.txt'),indexable?'User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: https://supploid.com/sitemap.xml\n':'User-agent: *\nDisallow: /\n');
console.log(`Generated ${pages.length} social cards, sitemap, and robots.txt (${indexable?'indexable':'preview / noindex'}).`);
